server:
  extraArgs:
    - --insecure
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: false

extraObjects:
  - apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      name: argocd-tls
      namespace: argocd
    spec:
      secretName: argocd-tls
      issuerRef:
        name: local-pki-issuer
        kind: ClusterIssuer
      commonName: argocd.mz4.re
      dnsNames:
        - argocd.mz4.re

  - apiVersion: traefik.io/v1alpha1
    kind: IngressRoute
    metadata:
      name: argocd-server
      namespace: argocd
    spec:
      entryPoints:
        - websecure
      routes:
      - match: Host(`argocd.mz4.re`)
        kind: Rule
        services:
        - name: argocd-server
          port: 80
      tls:
        secretName: argocd-tls

configs:
  cm:
    url: "https://argocd.mz4.re" 
    dex.config: |
      connectors:
      - type: ldap
        id: lldap
        name: LLDAP
        config:
          host: lldap.lldap.svc.cluster.local:3890
          insecureNoSSL: true
          insecureSkipVerify: true
          
          bindDN: "uid=admin,ou=people,dc=mz4,dc=re"
          bindPW: "changeme"
          
          userSearch:
            baseDN: "ou=people,dc=mz4,dc=re"
            filter: "(objectClass=person)"
            username: uid
            idAttr: uid
            emailAttr: mail
            nameAttr: displayName
            
          groupSearch:
            baseDN: "ou=groups,dc=mz4,dc=re"
            filter: "(objectClass=groupOfUniqueNames)"
            userMatchers:
            - userAttr: uid
              groupAttr: member
            nameAttr: cn

  rbac:
    policy.default: role:readonly
    policy.csv: |
      g, argocd-admins, role:admin
    scopes: '[groups]'